[metadata.heroku]
  root-package = "hunie"
  go-version = "go1.10"
  install = [ "./..." ]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.0"
